name: Python CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/

    # You can also add a debugging step to check for environment issues:
    - name: Debug Info
      run: |
        echo "Python Version: $(python --version)"
        echo "Pip Version: $(pip --version)"
        echo "Installed Packages:"
        pip freeze
